### ISSUE TITLE
Implement logging configuration

### ISSUE THREAD

**Issue by ryanolee** [ryanolee/go-pot#12]
# What
Currently control over what is logged and when it is logged is hard to , ideally things need to be improved on this front including adding more specific configuration for logging. Adding trace ID's to logs and having the ability to log  requests and push them to a local file or similar should be configurable from the app

**Comment by t3chn0m4g3** [comment]
Yippie 🙌🥳

**Comment by ryanolee** [comment]
Will get FTP command logging in a similar way and get it bundled into a 1.0 full release

**Comment by ryanolee** [comment]
Created https://github.com/ryanolee/go-pot/releases/tag/v1.0.0-rc6 @t3chn0m4g3  with the logging improvements in. Let me know if you run into any issues with the new config or have any further questions. Moving to close for now :clap:

**Comment by t3chn0m4g3** [comment]
@ryanolee Thanks, starting testing now.

**Comment by t3chn0m4g3** [comment]
@ryanolee Thanks for all the fields / features you added!

I am having difficulties enabling the access log fields ...:
```
[...]

# Configuration reference file for go-pot
# Please refer to config/config.go for more specifics on each field
# Each value is the default value for the field if not specified in the configuration file

# Configuration for the go-pot server
server:
  # If the http staller should be enabled
  enabled: true

  # Port for the go-pot server to listen on
  port: 8080

  # Host for the go-pot server to listen on
  host: 127.0.0.1

  # The network stack to listen on. One of: tcp, tcp4, tcp6
  network: "tcp4"

  # Trusted proxies for the server. This is a comma separated list of CIDR ranges, or Ip addresses (v4 or v6)
  trusted_proxies: ""

  # The header to use for the proxy header. This is the header that will be used to determine the IP address of the client
  proxy_header: "X-Forwarded-For"

  # Configuration related to access logging for the server
  access_log:

    # Given the nature of how requests are designed to hang by this service
    # there are a number of different ways to log requests. The following are the available modes
    #  - end: Logs the request after the request has been completed
    #  - start: Logs the request as soon as the request is received
    #  - both: Logs the request at both the start and the end of the request
    #  - none: Disables access logging
    mode: "both"

    # The path to write the access log to. If this is not specified then the access log will be written to stdout
    path: "/opt/go-pot/log/go-pot.json"

    # Comma deliminated list of fields to log. The following fields are available:
    #   - id: UUIDv4 generated for the request
    #   - timestamp: The time the request was received in RFC3339 format
    #   - status: The status code of the request
    #   - src_ip: The ip of the connecting client
    #   - method: The HTTP method of the request
    #   - path: The path of the request
    #   - qs: The query string of the request
    #   - dest_port: The port the request was sent to
    #   - type: The type of request (Always http)
    #   - host: The host of the request
    #   - user_agent: The user agent of the client
    #   - browser: The browser of the client (Inferred from the user agent)
    #   - browser_version: The version of the browser (Inferred from the user agent)
    #   - os: The operating system of the client (Inferred from the user agent)
    #   - os_version: The version of the operating system (Inferred from the user agent)
    #   - device: The device of the client (Inferred from the user agent)
    #   - device_brand: The type of device of the client (Inferred from the user agent)
    #   - phase: "start" or "end" depending on the phase of the request
    #   - duration: The duration of the request in milliseconds (Only available as a part of the end phase of a request)
    #fields: "src_ip,method,path,qs,duration"
    fields: "timestamp,id,status,src_ip,method,path,qs,dest_port,type,host,user_agent,browser,browser_version,os,os_version,device,device_brand,phase,duration"

[...]
```

The config file (in my case `config.yml` loaded via `--config-file`) is loaded at startup, the server starts without error and yet the fields are not written as expected. Here the result running go-pot and accessing it with a browser on `tcp/8080`:
```
{"level":"info","ts":1732801067.0609226,"caller":"logging/http_access_logger.go:249","msg":"","src_ip":"172.20.254.111","method":"GET","path":"/aws/.secrets","qs":"","duration":""}
{"level":"info","ts":1732801067.1629248,"caller":"logging/http_access_logger.go:249","msg":"","src_ip":"172.20.254.111","method":"GET","path":"/aws/.secrets","qs":"","duration":"101.785065ms"}
{"level":"info","ts":1732801067.6929152,"caller":"logging/http_access_logger.go:249","msg":"","src_ip":"172.20.254.111","method":"GET","path":"/favicon.ico","qs":"","duration":""}
{"level":"info","ts":1732801067.7974432,"caller":"logging/http_access_logger.go:249","msg":"","src_ip":"172.20.254.111","method":"GET","path":"/favicon.ico","qs":"","duration":"103.720642ms"}
```

I do not want to rule out that I am doing something wrong, but since anything else works fine maybe I missed something.

Do you have an idea?

**Comment by ryanolee** [comment]
Will check might be issues with config file values overriding default values 🤔

**Comment by ryanolee** [comment]
Ok I just pushed a fix. Was just a documentation issue :sweat_smile: . Should be `fields_to_log` not `fields`. You don't need to make any changes to anything other than the that config key (see)
```yaml
# Configuration for the go-pot server
server:
  # If the http staller should be enabled
  enabled: true

  # Port for the go-pot server to listen on
  port: 8080

  # Host for the go-pot server to listen on
  host: 127.0.0.1

  # The network stack to listen on. One of: tcp, tcp4, tcp6
  network: "tcp4"

  # Trusted proxies for the server. This is a comma separated list of CIDR ranges, or Ip addresses (v4 or v6)
  trusted_proxies: ""

  # The header to use for the proxy header. This is the header that will be used to determine the IP address of the client
  proxy_header: "X-Forwarded-For"

  # Configuration related to access logging for the server
  access_log:

    # Given the nature of how requests are designed to hang by this service
    # there are a number of different ways to log requests. The following are the available modes
    #  - end: Logs the request after the request has been completed
    #  - start: Logs the request as soon as the request is received
    #  - both: Logs the request at both the start and the end of the request
    #  - none: Disables access logging
    mode: "both"

    # The path to write the access log to. If this is not specified then the access log will be written to stdout
    path: "./go-pot.json"

    # Comma deliminated list of fields to log. The following fields are available:
    #   - id: UUIDv4 generated for the request
    #   - timestamp: The time the request was received in RFC3339 format
    #   - status: The status code of the request
    #   - src_ip: The ip of the connecting client
    #   - method: The HTTP method of the request
    #   - path: The path of the request
    #   - qs: The query string of the request
    #   - dest_port: The port the request was sent to
    #   - type: The type of request (Always http)
    #   - host: The host of the request
    #   - user_agent: The user agent of the client
    #   - browser: The browser of the client (Inferred from the user agent)
    #   - browser_version: The version of the browser (Inferred from the user agent)
    #   - os: The operating system of the client (Inferred from the user agent)
    #   - os_version: The version of the operating system (Inferred from the user agent)
    #   - device: The device of the client (Inferred from the user agent)
    #   - device_brand: The type of device of the client (Inferred from the user agent)
    #   - phase: "start" or "end" depending on the phase of the request
    #   - duration: The duration of the request in milliseconds (Only available as a part of the end phase of a request)
    #fields: "src_ip,method,path,qs,duration"
    fields_to_log: "timestamp,id,status,src_ip,method,path,qs,dest_port,type,host,user_agent,browser,browser_version,os,os_version,device,device_brand,phase,duration"
```
