### ISSUE TITLE
nFPM

### ISSUE THREAD

**Issue by necrose99** [ryanolee/go-pot#7]
nfpm 

https://nfpm.goreleaser.com/
https://github.com/goreleaser/nfpm 
https://github.com/burningalchemist/action-gh-nfpm

`[.nfpm.yaml}`

```
name: go-pot
# We'll use a template for arch
arch: ${ARCH}
platform: linux
version: v0.1.0
section: net
priority: optional
maintainer: Ryan O'Lee <ryan@example.com>
description: |
  go-pot 🍯 is a Go-based HTTP tarpit designed to frustrate and slow down malicious bots.
  It works by feeding bots an infinite stream of fake secrets at an excruciatingly slow rate,
  wasting their time and resources. This tool can help protect your web services from
  aggressive crawling, brute-force attacks, and other bot-based threats.
vendor: Ryan O'Lee
homepage: https://github.com/ryanolee/go-pot
license: MIT

# Target-specific overrides
overrides:
  deb:
    depends:
      - libc6
  rpm:
    depends:
      - glibc
  apk:
    depends:
      - libc6-compat
  archlinux:
    depends:
      - glibc
    replaces:
      - go-pot-git
    provides:
      - go-pot

# Arch-specific dependencies
overrides:
  archlinux:aarch64:
    depends:
      - glibc
  archlinux:armv7h:
    depends:
      - glibc-armhf

contents:
  - src: ./build/go-pot-${ARCH}
    dst: /usr/bin/go-pot
  - src: ./configs/go-pot.yaml
    dst: /etc/go-pot/config.yaml
  - src: ./scripts/go-pot.service
    dst: /usr/lib/systemd/system/go-pot.service
  - src: ./LICENSE
    dst: /usr/share/licenses/go-pot/LICENSE
  - src: ./README.md
    dst: /usr/share/doc/go-pot/README.md

scripts:
  postinstall: ./scripts/postinstall.sh
  preremove: ./scripts/preremove.sh

empty_folders:
  - /var/log/go-pot
```
